# Generated by Django 3.0.8 on 2021-02-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='background',
        ),
    ]
