# Generated by Django 3.0.8 on 2021-06-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_qoute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qoute',
            new_name='Qoutes',
        ),
    ]
