# Generated by Django 3.0.8 on 2021-07-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210617_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='inspiration', max_length=60),
        ),
    ]
