# Generated by Django 3.0.8 on 2021-07-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
